[package]
name = "quick-xmltodict"
version = "0.1.0"
edition = "2021"

[lib]
name = "quick_xmltodict"
crate-type = ["cdylib"]

[dependencies]
anyhow = "*"
pyo3 = { version = "*", features = ["anyhow"] }
quick-xml = "*"
